### ISSUE TITLE
CONGA Segmentation fault

### ISSUE THREAD

**Issue by iseultj** [asylvz/CONGA#1]
Hi, I'm getting a segmentation fault when trying to run CONGA.

This is the command I used:

`~/programs/CONGA/conga --input ${id}.bam--out ${id}_conga --ref /Reference_Genomes/hs37d5/hs37d5.fa --sonic human_g1k_v37.sonic --dels 1kGP_SV_del.Phase3.AFR_seg.bed --dups 1kGP_SV_dup.Phase3.AFR_seg.bed --mappability EncodeCrgMapabilityAlign100mer.bed`

It crashes when calculating likelihoods; when I run addr2line, this is where it points to:

`addr2line -e ~/programs/CONGA/conga 000000000040737d `
`/home/iseult/programs/CONGA/likelihood.c:120`

I downloaded CONGA on 5th April, and the version I'm using is 0.1

**Comment by asylvz** [comment]
Hi, which chromosome is it running when it segfaults? I'm not sure but I suspect it might be an issue related to the difference with your reference genome and the sonic file.

I can check it if you can provide me your bam and genotype files.

**Comment by iseultj** [comment]
Thanks! It's crashing on chr1. I'll email the files now

**Comment by iseultj** [comment]
Fixed by using bed files provided by @asylvz
